spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/license?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    enabled: true
    encoding: utf-8
    mode: HTML
    cache: false

mybatis:
  configuration:
    jdbc-type-for-null: null
  type-aliases-package: "com.license.gldnif.model"

server:
  port: 8080

